var windowwidth = $(window).width();
var htmlscale800 = windowwidth / 872 ;
var htmlscale700 = windowwidth / 872 ;
var addthispercent = 800*100/windowwidth-100 ;
var htmlstyle2 = '<style> html {width: 872px  !important; transform-origin: 0px 0px 0px !important; transform: translate(0px, 0px) scale(' + htmlscale800 + ');} .at-share-dock.atss{bottom: -'+addthispercent+'% !important;} #menu ul li a {padding: 0px 8px !important;} .row {width: 870px !important;} #content-wrapper {margin: 15px auto !important;} #main-wrapper {width: 99% !important; margin-left: 1%;} .index .post{padding: 8px 0 !important;} .sidebar-wrapper {width: 98% !important;} .item .post-body, .static_page .post-body{font-size: 25px !important;} #sidebar2 ,#sidebar_tabs ,#sidebar{width: 49%;} #sidebar2, #sidebar{float: left;} #sidebar_tabs{float: right;} .ads-place {width: 728px !important;}</style>' ;
var htmlstyle3 = '<style> html {width: 872px  !important; transform-origin: 0px 0px 0px !important; transform: translate(0px, 0px) scale(' + htmlscale700 + ');} .at-share-dock.atss{bottom: -'+addthispercent+'% !important;} #menu ul li a {padding: 0px 4px !important; font-size: 18px !important;} .row {width: 870px !important;} #content-wrapper {margin: 15px auto !important;} #main-wrapper {width: 99% !important; margin-left: 1%;} .index .post{padding: 8px 0 !important;} .sidebar-wrapper {width: 98% !important;} .item .post-body, .static_page .post-body{font-size: 25px !important;} #sidebar2 ,#sidebar_tabs ,#sidebar{width: 49%;} #sidebar2, #sidebar{float: left;} #sidebar_tabs{float: right;} .ads-place {width: 728px !important;} .block-image {width: 350px!important;height: 223px!important;}.block-image .thumb a {height: 223px!important;}.block-image .thumb {height: 223px!important;}.post h2 a {font-size: 30px!important;}.date-header {font-size: 15px!important;}.resumo span {font-size: 15px!important;}.resumo a {font-size: 20px!important;}#subscribebox {font-size: 19px!important;}.tab-opt li a {font-size: 19px!important;}.item-title {font-size: 22px!important;}.item-thumbnail {width: 150px!important;height: 105px!important;}.footer-wrapper .copyright {font-size: 20px!important;margin-left: 2%!important;}body {font-size: 20px!important;}.sidebar h2 {font-size: 20px!important;}#slected-posts-list ul div div a img {width: 150px !important;height: 105px !important;}#blog-pager a {font-size: 20px !important;}</style>' ;


if(windowwidth > 872 && windowwidth <= 1171) {$('head').append('<style>.row {width: 870px !important;} #menu ul li a {font-size: 11px !important;} #main-wrapper {margin-left: 2% !important;} .ads-place {width: 728px !important;} #content-wrapper {width: 70% !important;}</style>');};
if(windowwidth > 399 && windowwidth <= 872) {$('head').append(htmlstyle2);};
if(windowwidth > 0 && windowwidth <= 399) {$('head').append(htmlstyle3);};
